// export const metadata = {
//     title: "edkj",
//     description: "Generated by nexsfsndjnfjdsn.js",

import Link from "next/link";

  
// };

export default function Home()
{

   
    return( 
    <>
    <h1>Welcome to home page!</h1>;
    <Link href="/blog">About</Link>
    <Link href="/contact">Contact</Link>
    
    </>
)}